### ISSUE TITLE
Has-previous doesn't work when paging forward.

### ISSUE THREAD

**Issue by danpalmer** [photocrowd/django-cursor-pagination#17]
Given a set of 10 items, and the query "first 3 after 4", I'd expect the return value to have `has_next=True` and `has_previous=True`, but it only has `has_next=True`.

**Comment by danpalmer** [comment]
Ah, it looks like @moggers87 has already implemented this in #16. Could that be merged and released? Would be very handy as we're using this _outside_ of Relay for the moment and need these values to be populated correctly.

**Comment by moggers87** [comment]
FWIW, I'm not using this package for anything GraphQL related either

@danpalmer if you can't (or don't want to) install from git, it's fairly easy to work around this bug by subclassing the `CursorPaginator` and overriding the `page` method.

**Comment by danpalmer** [comment]
Thanks, good idea. I've included the PR patch locally in our code for now.

**Comment by moggers87** [comment]
I think this issue can be closed now as #16 has been merged and released.
