### ISSUE TITLE
Using OrderBy objects does not work

### ISSUE THREAD

**Issue by Drarok** [photocrowd/django-cursor-pagination#18]
Since the direction of the sorts are checked assuming they are strings ([source](https://github.com/photocrowd/django-cursor-pagination/blob/13ec85507894daf8f0a7ee8727964a1242009281/cursor_pagination.py#L70)), attempting to use an OrderBy object will cause a crash.

The use of an OrderBy object is required in order to change how null values are sorted ([source](https://docs.djangoproject.com/en/2.0/ref/models/expressions/#using-f-to-sort-null-values))
```py
qs.order_by(F('field_name').desc(nulls_last=True))
```

**Comment by thommor** [comment]
Closing as fixed in #44
