### ISSUE TITLE
Pagination doesn't work with mongoengine

### ISSUE THREAD

**Issue by jaisharma639** [photocrowd/django-cursor-pagination#32]
Since mongoengine doesn't support django annotate, the following exception occurs when trying to paginate.
`'QuerySet' object has no attribute 'annotate'`
in the following line:
`queryset = queryset.annotate(_cursor=Tuple(*[o.lstrip('-') for o in self.ordering]))`

**Comment by moggers87** [comment]
If the database backend doesn't support annotate, that's a bug in the database backend not django-cursor-pagination

**Comment by mjtamlyn** [comment]
Pretty sure tuple ordering won't work on mongodb anyway.
