### ISSUE TITLE
Major Issue:  Breaks on Django 3.1.7

### ISSUE THREAD

**Issue by EmperorArthur** [photocrowd/django-cursor-pagination#38]
Hello,
This package is broken on Django version 3.1.7.  Which is at least the latest stable release of Django.

# Example code:
```python
from cursor_pagination import CursorPaginator
```
## Result:
"ImportError: cannot import name 'six' from 'django.utils'"
## Expected Result:
CursorPaginator imported successfully.

**Comment by dorianamouroux** [comment]
This import was removed there: https://github.com/photocrowd/django-cursor-pagination/commit/1ebc4aba54d84ac4359cd38b81c3cc4ee659bd61#diff-0ce18fd053e85c304cc64c8258cf448b716a509280048d7b84fc76b9e590c317 so maybe you can install via that commit until a new version is made?

**Comment by sepira** [comment]
Any idea when will this be fixed?

**Comment by lvieirajr** [comment]
@Drarok @mjtamlyn @patrick91 any chance we can get a new version 0.1.5 released?
The fix for this issue is already merged onto master.

**Comment by patrick91** [comment]
@lvieirajr I'm sorry but I don't have permession to release, I was consindering making a new package/fork to keep it alive.

**Comment by lvieirajr** [comment]
Who are the people that can make the releases? Are they just not maintaining this anymore?
Could you at least get them to give you access to make the release so this doesn't die?

**Comment by Drarok** [comment]
@patrick91 I don't have commit access to this repo anymore, but I am still listed as an owner of the [package on pypi][package]. I can add you as a maintainer, what's your username?

Edit: There's a `patrick91` user with the same profile picture, I assume that's you.

[package]: https://pypi.org/manage/project/django-cursor-pagination/collaboration/

**Comment by patrick91** [comment]
@Drarok yes, that's me :)

**Comment by patrick91** [comment]
Got access! I'll try to make a release by the end of the weekend!

**Comment by dorian-writes-code** [comment]
Hey @patrick91 ; do you have any future plans for that repos; or will you only do a one-off release to address the problem from that issue?

If you plan on being a maintained; there is a couple of features I would love to help building

**Comment by patrick91** [comment]
@dorian-writes-code I'm happy to maintain it, but I don't think I'll work on any new features personally. 

Happy to review your PRs though! What did you have in mind?

**Comment by dorian-writes-code** [comment]
One issue I've had is that when ordering a column from the highest value to the lowest; `NULL` values from the column would appear first. 

With `order_by`; it's possible to choose if the `null` should be first or last (https://docs.djangoproject.com/en/3.2/ref/models/querysets/#order-by); so I would like to be able to have that option in django-cursor-pagination

**Comment by lvieirajr** [comment]
Yay @patrick91 the savior! Thanks @Drarok

**Comment by patrick91** [comment]
Release ready here: https://pypi.org/project/django-cursor-pagination/0.1.5/

let me know if there's any issue 😊
