### ISSUE TITLE
django-cursor-pagination not compatible with  django-mock-queries

### ISSUE THREAD

**Issue by habibi1981** [photocrowd/django-cursor-pagination#42]
I'm using django-cursor-pagination for queryset  pagination, and for testing my code I'm using the django-mock-queries package for  mock queryset , this packages not compatible with each other.

https://pypi.org/project/django-mock-queries/

**Comment by patrick91** [comment]
hi @habibi1981 can you define a bit what you mean by not being compatible? do you get any errors? if so what errors? 

do you also have some code to reproduce this? I have never used django mock queries :)
