### ISSUE TITLE
Fails to handle multliple ordering fields properly

### ISSUE THREAD

**Issue by mjtamlyn** [photocrowd/django-cursor-pagination#6]
We need to ensure that only the last field is `__lt` or `__gt`, the previous ones should be `__lte`.

As an example, order on `('a', 'b')`, page at 2.

Data:

```
 a | b 
 1 | 2
 1 | 3
 1 | 4
 2 | 1
```

"second" page will return only the last element.

**Comment by danpalmer** [comment]
Can this issue be closed?
