### ISSUE TITLE
Consider providing a REST framework pagination class for this package.

### ISSUE THREAD

**Issue by lovelydinosaur** [photocrowd/django-cursor-pagination#9]
Based on our conversation about this, I think your simpler implementation may well be a better approach to cursor pagination that the default provided by REST framework. It'd certainly be valuable to have this scheme easily available to REST framework users.

Any thoughts on if you'd consider a REST framework pagination class for this package?

**Comment by merwok** [comment]
Hello!  I am curious about the discussion alluded to here.  Should people build a DRF pagination class on top of this package instead of using the CursorPagination class from DRF 3?

**Comment by lovelydinosaur** [comment]
You could build a DRF pagination class on top of this package yup. I opened the issue originally speculating on if it'd be worth including one in the package itself.

I'll close off this issue, given staleness - obviously not something that'll happen within the package itself. However a well-documented third party package taking it on would be very welcome!
